# golangci-lint configuration v2
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false  # Don't run linters on test files

linters:
  default: none
  enable:
    # Core linters - must pass
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter (includes gosimple)

    # Code quality
    - misspell      # Fix spelling errors
    - unconvert     # Remove unnecessary type conversions

    # Security
    - gosec         # Security checks

  exclusions:
    # Exclude examples directory
    paths:
      - examples

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - (*encoding/json.Decoder).Decode
        - (io.Closer).Close
        - os.Setenv
        - os.Unsetenv
        - fmt.Fprintf
        - fmt.Scanln

    staticcheck:
      checks:
        - "all"
        - "-SA9003"  # Disable empty branch check
        - "-SA1019"  # Disable deprecation warnings (we have deprecated methods for compatibility)
        - "-QF1008"  # Disable embedded field selector suggestion
        - "-ST1020"  # Disable comment format check

    govet:
      disable:
        - shadow        # Too noisy
        - fieldalignment  # Micro-optimization

    misspell:
      locale: US
      ignore-rules:
        - cancelled   # UK spelling used in Jira API
        - favourite   # UK spelling used in Jira API
        - analyse     # UK spelling used in Jira API

    gosec:
      excludes:
        - G104  # Unhandled errors (covered by errcheck with exclusions)

formatters:
  enable:
    - gofmt

  settings:
    gofmt:
      simplify: true
